<?php
/**
 * TESTE RPA DEBUG - VERSÃO PARA INVESTIGAR PROBLEMAS
 */

echo "<!DOCTYPE html>";
echo "<html lang='pt-BR'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>Teste RPA Debug</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }";
echo "        .container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; }";
echo "        .progress-bar { width: 100%; height: 30px; background: #e0e0e0; border-radius: 15px; overflow: hidden; }";
echo "        .progress-fill { height: 100%; background: #4CAF50; transition: width 0.5s ease; width: 0%; }";
echo "        .status { margin: 15px 0; font-size: 18px; text-align: center; }";
echo "        button { padding: 15px 30px; background: #4CAF50; color: white; border: none; border-radius: 5px; cursor: pointer; margin: 10px; }";
echo "        button:disabled { background: #ccc; }";
echo "        .log { background: #f8f9fa; padding: 15px; margin-top: 20px; max-height: 400px; overflow-y: auto; }";
echo "        .log-entry { margin: 5px 0; padding: 5px; background: white; border-radius: 3px; }";
echo "        .debug { background: #fff3cd; border-left: 4px solid #ffc107; }";
echo "    </style>";
echo "</head>";
echo "<body>";
echo "    <div class='container'>";
echo "        <h1>🔍 Teste RPA Debug</h1>";
echo "        <p>Versão para investigar problemas de conexão SSE</p>";
echo "";
echo "        <div class='progress-bar'>";
echo "            <div class='progress-fill' id='progress-bar'></div>";
echo "        </div>";
echo "        <div class='status' id='status'>Aguardando início...</div>";
echo "";
echo "        <div style='text-align: center;'>";
echo "            <button onclick='iniciarRPA()' id='btn-iniciar'>🚀 Iniciar RPA Debug</button>";
echo "            <button onclick='pararTeste()' id='btn-parar' disabled>🛑 Parar</button>";
echo "        </div>";
echo "";
echo "        <div class='log' id='log'>";
echo "            <h3>Log de Eventos (Debug)</h3>";
echo "            <div id='log-entries'></div>";
echo "        </div>";
echo "    </div>";
echo "";
echo "    <script>";
echo "        let eventSource = null;";
echo "        let sessionId = 'debug_' + Math.random().toString(36).substr(2, 9);";
echo "        let messageCount = 0;";
echo "";
echo "        function log(message, isDebug = false) {";
echo "            const logContainer = document.getElementById('log-entries');";
echo "            const timestamp = new Date().toLocaleTimeString();";
echo "            const entry = document.createElement('div');";
echo "            entry.className = 'log-entry' + (isDebug ? ' debug' : '');";
echo "            entry.innerHTML = '<strong>[' + timestamp + ']</strong> ' + message;";
echo "            logContainer.appendChild(entry);";
echo "            logContainer.scrollTop = logContainer.scrollHeight;";
echo "        }";
echo "";
echo "        function iniciarRPA() {";
echo "            if (eventSource) {";
echo "                log('⚠️ RPA já está em execução');";
echo "                return;";
echo "            }";
echo "";
echo "            messageCount = 0;";
echo "            log('🚀 Iniciando RPA debug...');";
echo "            log('🌐 Chrome será aberto automaticamente');";
echo "";
echo "            document.getElementById('btn-iniciar').disabled = true;";
echo "            document.getElementById('btn-parar').disabled = false;";
echo "            document.getElementById('status').textContent = 'Conectando...';";
echo "";
echo "            const url = 'progress_sse_debug.php?session_id=' + sessionId;";
echo "            log('🔗 Conectando em: ' + url, true);";
echo "            eventSource = new EventSource(url);";
echo "";
echo "            eventSource.onopen = function() {";
echo "                log('✅ Conexão estabelecida');";
echo "            };";
echo "";
echo "            eventSource.onmessage = function(event) {";
echo "                messageCount++;";
echo "                log('📨 Mensagem #' + messageCount + ' recebida', true);";
echo "                try {";
echo "                    const data = JSON.parse(event.data);";
echo "                    log('📊 Dados: ' + JSON.stringify(data, null, 2), true);";
echo "                    processarMensagem(data);";
echo "                } catch (error) {";
echo "                    log('❌ Erro ao processar: ' + error.message);";
echo "                }";
echo "            };";
echo "";
echo "            eventSource.onerror = function(error) {";
echo "                log('❌ Erro na conexão: ' + JSON.stringify(error), true);";
echo "                pararTeste();";
echo "            };";
echo "        }";
echo "";
echo "        function processarMensagem(data) {";
echo "            log('📨 ' + (data.status || 'progresso') + ': ' + (data.message || data.status || 'atualizando'));";
echo "";
echo "            if (data.status === 'starting') {";
echo "                document.getElementById('status').textContent = '🚀 Iniciando RPA...';";
echo "                atualizarProgresso(0);";
echo "            } else if (data.status === 'started') {";
echo "                document.getElementById('status').textContent = '🌐 Chrome aberto - RPA executando...';";
echo "                log('🎭 Playwright abriu Chrome!');";
echo "            } else if (data.status === 'completed') {";
echo "                document.getElementById('status').textContent = '✅ RPA concluído!';";
echo "                atualizarProgresso(100);";
echo "                log('🎉 RPA executado com sucesso!');";
echo "                pararTeste();";
echo "            } else if (data.status === 'timeout') {";
echo "                document.getElementById('status').textContent = '⏰ Timeout';";
echo "                log('⏰ Timeout atingido');";
echo "                pararTeste();";
echo "            } else if (data.status === 'error') {";
echo "                document.getElementById('status').textContent = '❌ Erro';";
echo "                log('❌ Erro: ' + data.message);";
echo "                pararTeste();";
echo "            } else if (data.status === 'heartbeat' || data.status === 'waiting') {";
echo "                log('💓 ' + data.message + ' (Debug: ' + data.debug + ')', true);";
echo "            } else if (data.etapa_atual !== undefined) {";
echo "                const percentual = Math.round(data.percentual || 0);";
echo "                const etapa = data.etapa_atual || 0;";
echo "                const status = data.status || 'Processando...';";
echo "";
echo "                atualizarProgresso(percentual);";
echo "                document.getElementById('status').textContent = status + ' (' + etapa + '/15)';";
echo "                log('📊 Etapa ' + etapa + ': ' + status + ' (' + percentual + '%)');";
echo "            }";
echo "        }";
echo "";
echo "        function atualizarProgresso(percentual) {";
echo "            document.getElementById('progress-bar').style.width = percentual + '%';";
echo "        }";
echo "";
echo "        function pararTeste() {";
echo "            if (eventSource) {";
echo "                eventSource.close();";
echo "                eventSource = null;";
echo "                log('🛑 Monitoramento parado');";
echo "            }";
echo "";
echo "            document.getElementById('btn-iniciar').disabled = false;";
echo "            document.getElementById('btn-parar').disabled = true;";
echo "        }";
echo "";
echo "        window.onload = function() {";
echo "            log('📱 Página carregada - Pronto para executar RPA debug');";
echo "            log('💡 Clique em \"Iniciar RPA Debug\" para investigar problemas');";
echo "        };";
echo "    </script>";
echo "</body>";
echo "</html>";
?>
