<?php
/**
 * TESTE COMPLETO - RPA REAL COM MONITORAMENTO TEMPO REAL
 * Executa o RPA Python real e monitora via PHP
 */

echo "<!DOCTYPE html>";
echo "<html lang='pt-BR'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>Teste RPA Real - Monitoramento Tempo Real</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }";
echo "        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }";
echo "        .header { text-align: center; margin-bottom: 30px; }";
echo "        .progress-container { margin: 20px 0; }";
echo "        .progress-bar { width: 100%; height: 40px; background: #e0e0e0; border-radius: 20px; overflow: hidden; position: relative; }";
echo "        .progress-fill { height: 100%; background: linear-gradient(90deg, #4CAF50, #8BC34A); transition: width 0.5s ease; width: 0%; position: relative; }";
echo "        .progress-text { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); color: white; font-weight: bold; font-size: 16px; }";
echo "        .status-text { margin: 15px 0; font-size: 20px; font-weight: bold; text-align: center; color: #333; }";
echo "        .session-info { color: #666; font-size: 14px; text-align: center; margin-bottom: 20px; }";
echo "        .controls { text-align: center; margin: 20px 0; }";
echo "        button { padding: 15px 30px; background: #4CAF50; color: white; border: none; border-radius: 8px; cursor: pointer; margin: 10px; font-size: 16px; font-weight: bold; }";
echo "        button:hover { background: #45a049; }";
echo "        button:disabled { background: #ccc; cursor: not-allowed; }";
echo "        .log { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-top: 20px; max-height: 400px; overflow-y: auto; border: 1px solid #dee2e6; }";
echo "        .log-entry { margin: 8px 0; padding: 10px; background: white; border-radius: 6px; border-left: 4px solid #4CAF50; }";
echo "        .log-entry.error { border-left-color: #dc3545; background: #fff5f5; }";
echo "        .log-entry.warning { border-left-color: #ffc107; background: #fffbf0; }";
echo "        .log-entry.success { border-left-color: #28a745; background: #f0fff4; }";
echo "        .estimativas-box, .resultado-final { margin: 20px 0; padding: 25px; border: 2px solid #4CAF50; border-radius: 12px; background: linear-gradient(135deg, #f0fff4, #e8f5e8); }";
echo "        .planos-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px; }";
echo "        .plano-item { padding: 20px; border-radius: 12px; text-align: center; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }";
echo "        .plano-item.recomendado { background: linear-gradient(135deg, #e8f5e8, #c8e6c9); border: 3px solid #4CAF50; }";
echo "        .plano-item.alternativo { background: linear-gradient(135deg, #e3f2fd, #bbdefb); border: 3px solid #2196F3; }";
echo "        .valor-principal { font-size: 28px; font-weight: bold; margin: 15px 0; color: #2e7d32; }";
echo "        .franquia { color: #666; font-size: 16px; }";
echo "        .rpa-status { background: #e3f2fd; padding: 15px; border-radius: 8px; margin: 20px 0; text-align: center; }";
echo "        .chrome-info { background: #fff3e0; padding: 15px; border-radius: 8px; margin: 20px 0; text-align: center; border: 2px solid #ff9800; }";
echo "    </style>";
echo "</head>";
echo "<body>";
echo "    <div class='container'>";
echo "        <div class='header'>";
echo "            <h1>🎭 Teste RPA Real - Monitoramento Tempo Real</h1>";
echo "            <p>Execute o RPA Python real e acompanhe o progresso passo a passo</p>";
echo "        </div>";
echo "";
echo "        <div class='chrome-info'>";
echo "            <h3>🌐 Chrome será aberto automaticamente!</h3>";
echo "            <p>O Playwright abrirá uma janela do Chrome onde você poderá ver a execução em tempo real</p>";
echo "        </div>";
echo "";
echo "        <div class='progress-container'>";
echo "            <div class='progress-bar'>";
echo "                <div class='progress-fill' id='progress-bar'>";
echo "                    <div class='progress-text' id='progress-text'>0%</div>";
echo "                </div>";
echo "            </div>";
echo "            <div class='status-text' id='status-text'>Aguardando início...</div>";
echo "            <div class='session-info' id='session-info'></div>";
echo "        </div>";
echo "";
echo "        <div id='estimativas-container' style='display: none;'></div>";
echo "        <div id='resultado-container' style='display: none;'></div>";
echo "";
echo "        <div class='controls'>";
echo "            <button onclick='iniciarRPAReal()' id='btn-iniciar'>🚀 Iniciar RPA Real</button>";
echo "            <button onclick='pararTeste()' id='btn-parar' disabled>🛑 Parar</button>";
echo "        </div>";
echo "";
echo "        <div class='rpa-status' id='rpa-status'>";
echo "            <h3>Status do RPA</h3>";
echo "            <p id='rpa-info'>Aguardando comando...</p>";
echo "        </div>";
echo "";
echo "        <div class='log' id='log-container'>";
echo "            <h3>📋 Log de Eventos em Tempo Real</h3>";
echo "            <div id='log-entries'></div>";
echo "        </div>";
echo "    </div>";
echo "";
echo "    <script>";
echo "        let eventSource = null;";
echo "        let sessionId = null;";
echo "        let rpaProcess = null;";
echo "";
echo "        function gerarSessionId() {";
echo "            return 'rpa_real_' + Math.random().toString(36).substr(2, 9);";
echo "        }";
echo "";
echo "        function log(message, type = 'info') {";
echo "            const logContainer = document.getElementById('log-entries');";
echo "            const timestamp = new Date().toLocaleTimeString();";
echo "            const entry = document.createElement('div');";
echo "            entry.className = `log-entry ${type}`;";
echo "            entry.innerHTML = `<strong>[${timestamp}]</strong> ${message}`;";
echo "            logContainer.appendChild(entry);";
echo "            logContainer.scrollTop = logContainer.scrollHeight;";
echo "        }";
echo "";
echo "        function iniciarRPAReal() {";
echo "            if (eventSource) {";
echo "                log('⚠️ RPA já está em execução', 'warning');";
echo "                return;";
echo "            }";
echo "";
echo "            sessionId = gerarSessionId();";
echo "            log(`🚀 Iniciando RPA real com sessão: ${sessionId}`, 'success');";
echo "            log('🌐 Chrome será aberto automaticamente pelo Playwright', 'info');";
echo "";
echo "            // Atualizar UI";
echo "            document.getElementById('btn-iniciar').disabled = true;";
echo "            document.getElementById('btn-parar').disabled = false;";
echo "            document.getElementById('status-text').textContent = 'Conectando ao RPA...';";
echo "            document.getElementById('session-info').textContent = `Sessão: ${sessionId}`;";
echo "            document.getElementById('rpa-info').textContent = 'Iniciando processo Python...';";
echo "";
echo "            // Conectar ao SSE";
echo "            const url = `progress_sse.php?session_id=${sessionId}`;";
echo "            eventSource = new EventSource(url);";
echo "";
echo "            eventSource.onopen = function() {";
echo "                log('✅ Conexão SSE estabelecida', 'success');";
echo "                log('🐍 Executando: python executar_rpa_imediato_playwright.py', 'info');";
echo "            };";
echo "";
echo "            eventSource.onmessage = function(event) {";
echo "                try {";
echo "                    const data = JSON.parse(event.data);";
echo "                    processarMensagem(data);";
echo "                } catch (error) {";
echo "                    log(`❌ Erro ao processar mensagem: ${error.message}`, 'error');";
echo "                }";
echo "            };";
echo "";
echo "            eventSource.onerror = function(error) {";
echo "                log('❌ Erro na conexão SSE', 'error');";
echo "                pararTeste();";
echo "            };";
echo "        }";
echo "";
echo "        function processarMensagem(data) {";
echo "            log(`📨 ${data.status || 'progresso'}: ${data.message || data.status || 'atualizando'}`, 'info');";
echo "";
echo "            switch (data.status) {";
echo "                case 'starting':";
echo "                    atualizarStatus('🚀 Iniciando RPA...');";
echo "                    atualizarProgresso(0);";
echo "                    document.getElementById('rpa-info').textContent = 'Processo Python iniciado';";
echo "                    break;";
echo "";
echo "                case 'started':";
echo "                    atualizarStatus('🌐 Chrome aberto - RPA executando...');";
echo "                    document.getElementById('rpa-info').textContent = 'Playwright executando no Chrome';";
echo "                    log('🎭 Playwright abriu Chrome - acompanhe a execução!', 'success');";
echo "                    break;";
echo "";
echo "                case 'completed':";
echo "                    atualizarStatus('✅ RPA concluído com sucesso!');";
echo "                    atualizarProgresso(100);";
echo "                    document.getElementById('rpa-info').textContent = 'Processo Python finalizado';";
echo "                    mostrarResultadoFinal(data.progresso);";
echo "                    log('🎉 RPA executado com sucesso!', 'success');";
echo "                    pararTeste();";
echo "                    break;";
echo "";
echo "                case 'timeout':";
echo "                    atualizarStatus('⏰ Timeout - RPA cancelado');";
echo "                    document.getElementById('rpa-info').textContent = 'Timeout atingido';";
echo "                    log('⏰ Timeout atingido', 'warning');";
echo "                    pararTeste();";
echo "                    break;";
echo "";
echo "                case 'error':";
echo "                    atualizarStatus('❌ Erro na execução do RPA');";
echo "                    document.getElementById('rpa-info').textContent = 'Erro no processo Python';";
echo "                    log(`❌ Erro: ${data.message}`, 'error');";
echo "                    pararTeste();";
echo "                    break;";
echo "";
echo "                default:";
echo "                    // Dados de progresso normal";
echo "                    if (data.etapa_atual !== undefined) {";
echo "                        processarProgresso(data);";
echo "                    }";
echo "                    break;";
echo "            }";
echo "        }";
echo "";
echo "        function processarProgresso(data) {";
echo "            const percentual = Math.round(data.percentual || 0);";
echo "            const etapa = data.etapa_atual || 0;";
echo "            const status = data.status || 'Processando...';";
echo "";
echo "            atualizarProgresso(percentual);";
echo "            atualizarStatus(`${status} (${etapa}/15)`);";
echo "";
echo "            log(`📊 Etapa ${etapa}: ${status} (${percentual}%)`, 'info');";
echo "";
echo "            // Mostrar estimativas na Etapa 5";
echo "            if (etapa === 5 && data.details && data.details.estimativas) {";
echo "                mostrarEstimativas(data.details.estimativas);";
echo "            }";
echo "";
echo "            // Atualizar status do RPA";
echo "            document.getElementById('rpa-info').textContent = `Executando etapa ${etapa}/15`;";
echo "        }";
echo "";
echo "        function atualizarProgresso(percentual) {";
echo "            const progressBar = document.getElementById('progress-bar');";
echo "            const progressText = document.getElementById('progress-text');";
echo "            progressBar.style.width = percentual + '%';";
echo "            progressText.textContent = percentual + '%';";
echo "        }";
echo "";
echo "        function atualizarStatus(texto) {";
echo "            document.getElementById('status-text').textContent = texto;";
echo "        }";
echo "";
echo "        function mostrarEstimativas(estimativas) {";
echo "            const container = document.getElementById('estimativas-container');";
echo "            container.innerHTML = `";
echo "                <div class='estimativas-box'>";
echo "                    <h3>📊 Estimativas Iniciais Capturadas</h3>";
echo "                    <div class='estimativas-grid'>";
echo "                        <div class='estimativa-item'>";
echo "                            <span class='label'><strong>Valor Estimado:</strong></span>";
echo "                            <span class='valor'>${estimativas.valor_estimado || 'N/A'}</span>";
echo "                        </div>";
echo "                        <div class='estimativa-item'>";
echo "                            <span class='label'><strong>Franquia:</strong></span>";
echo "                            <span class='valor'>${estimativas.franquia || 'N/A'}</span>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "            `;";
echo "            container.style.display = 'block';";
echo "            log('📊 Estimativas exibidas na tela', 'success');";
echo "        }";
echo "";
echo "        function mostrarResultadoFinal(progresso) {";
echo "            const container = document.getElementById('resultado-container');";
echo "            const planos = progresso.details?.planos || {};";
echo "";
echo "            container.innerHTML = `";
echo "                <div class='resultado-final'>";
echo "                    <h3>🎉 Cotação Concluída com Sucesso!</h3>";
echo "                    <div class='planos-grid'>";
echo "                        <div class='plano-item recomendado'>";
echo "                            <h4>🏆 Plano Recomendado</h4>";
echo "                            <div class='valor-principal'>" . ($planos['plano_recomendado']['valor'] ?? 'N/A') . "</div>";
echo "                            <div class='franquia'>Franquia: " . ($planos['plano_recomendado']['valor_franquia'] ?? 'N/A') . "</div>";
echo "                        </div>";
echo "                        <div class='plano-item alternativo'>";
echo "                            <h4>⭐ Plano Alternativo</h4>";
echo "                            <div class='valor-principal'>" . ($planos['plano_alternativo']['valor'] ?? 'N/A') . "</div>";
echo "                            <div class='franquia'>Franquia: " . ($planos['plano_alternativo']['valor_franquia'] ?? 'N/A') . "</div>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "            `;";
echo "            container.style.display = 'block';";
echo "            log('🎉 Resultado final exibido', 'success');";
echo "        }";
echo "";
echo "        function pararTeste() {";
echo "            if (eventSource) {";
echo "                eventSource.close();";
echo "                eventSource = null;";
echo "                log('🛑 Monitoramento parado', 'warning');";
echo "            }";
echo "";
echo "            document.getElementById('btn-iniciar').disabled = false;";
echo "            document.getElementById('btn-parar').disabled = true;";
echo "            document.getElementById('rpa-info').textContent = 'Aguardando comando...';";
echo "        }";
echo "";
echo "        // Limpar log ao carregar";
echo "        window.onload = function() {";
echo "            log('📱 Página carregada - Pronto para executar RPA real', 'success');";
echo "            log('💡 Clique em \"Iniciar RPA Real\" para executar o Playwright', 'info');";
echo "        };";
echo "    </script>";
echo "</body>";
echo "</html>";
?>
