<?php
/**
 * TESTE DA SOLUÇÃO HÍBRIDA
 * Testa o SSE endpoint e a funcionalidade completa
 */

echo "<!DOCTYPE html>";
echo "<html lang='pt-BR'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>Teste Progress Tracker</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; margin: 20px; }";
echo "        .container { max-width: 800px; margin: 0 auto; }";
echo "        .progress-container { margin: 20px 0; }";
echo "        .progress-bar { width: 100%; height: 30px; background: #f0f0f0; border-radius: 15px; overflow: hidden; }";
echo "        .progress-fill { height: 100%; background: linear-gradient(90deg, #4CAF50, #8BC34A); transition: width 0.3s ease; width: 0%; }";
echo "        .status-text { margin: 10px 0; font-size: 18px; font-weight: bold; }";
echo "        .session-info { color: #666; font-size: 14px; }";
echo "        .estimativas-box, .resultado-final { margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 8px; background: #f9f9f9; }";
echo "        .planos-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 15px; }";
echo "        .plano-item { padding: 15px; border-radius: 8px; text-align: center; }";
echo "        .plano-item.recomendado { background: #e8f5e8; border: 2px solid #4CAF50; }";
echo "        .plano-item.alternativo { background: #e8f4fd; border: 2px solid #2196F3; }";
echo "        .valor-principal { font-size: 24px; font-weight: bold; margin: 10px 0; }";
echo "        .franquia { color: #666; }";
echo "        .log { background: #f5f5f5; padding: 15px; border-radius: 8px; margin-top: 20px; max-height: 300px; overflow-y: auto; }";
echo "        .log-entry { margin: 5px 0; padding: 5px; background: white; border-radius: 4px; }";
echo "        button { padding: 10px 20px; background: #4CAF50; color: white; border: none; border-radius: 5px; cursor: pointer; margin: 10px 5px; }";
echo "        button:hover { background: #45a049; }";
echo "        button:disabled { background: #ccc; cursor: not-allowed; }";
echo "    </style>";
echo "</head>";
echo "<body>";
echo "    <div class='container'>";
echo "        <h1>Teste Progress Tracker - Solução Híbrida</h1>";
echo "        <p>Este teste demonstra a funcionalidade de monitoramento em tempo real do RPA.</p>";
echo "";
echo "        <div class='progress-container'>";
echo "            <div class='progress-bar'>";
echo "                <div class='progress-fill' id='progress-bar'></div>";
echo "            </div>";
echo "            <div class='status-text' id='status-text'>Aguardando início...</div>";
echo "            <div class='session-info' id='session-info'></div>";
echo "        </div>";
echo "";
echo "        <div id='estimativas-container' style='display: none;'></div>";
echo "        <div id='resultado-container' style='display: none;'></div>";
echo "";
echo "        <div>";
echo "            <button onclick='iniciarTeste()' id='btn-iniciar'>Iniciar Cotação</button>";
echo "            <button onclick='pararTeste()' id='btn-parar' disabled>Parar</button>";
echo "        </div>";
echo "";
echo "        <div class='log' id='log-container'>";
echo "            <h3>Log de Eventos</h3>";
echo "            <div id='log-entries'></div>";
echo "        </div>";
echo "    </div>";
echo "";
echo "    <script>";
echo "        let eventSource = null;";
echo "        let sessionId = null;";
echo "";
echo "        function gerarSessionId() {";
echo "            return 'test_' + Math.random().toString(36).substr(2, 9);";
echo "        }";
echo "";
echo "        function log(message) {";
echo "            const logContainer = document.getElementById('log-entries');";
echo "            const timestamp = new Date().toLocaleTimeString();";
echo "            const entry = document.createElement('div');";
echo "            entry.className = 'log-entry';";
echo "            entry.innerHTML = `<strong>[${timestamp}]</strong> ${message}`;";
echo "            logContainer.appendChild(entry);";
echo "            logContainer.scrollTop = logContainer.scrollHeight;";
echo "        }";
echo "";
echo "        function iniciarTeste() {";
echo "            if (eventSource) {";
echo "                log('⚠️ Teste já está em execução');";
echo "                return;";
echo "            }";
echo "";
echo "            sessionId = gerarSessionId();";
echo "            log(`🚀 Iniciando teste com sessão: ${sessionId}`);";
echo "";
echo "            // Atualizar UI";
echo "            document.getElementById('btn-iniciar').disabled = true;";
echo "            document.getElementById('btn-parar').disabled = false;";
echo "            document.getElementById('status-text').textContent = 'Conectando...';";
echo "            document.getElementById('session-info').textContent = `Sessão: ${sessionId}`;";
echo "";
echo "            // Conectar ao SSE";
echo "            const url = `progress_sse.php?session_id=${sessionId}`;";
echo "            eventSource = new EventSource(url);";
echo "";
echo "            eventSource.onopen = function() {";
echo "                log('✅ Conexão SSE estabelecida');";
echo "            };";
echo "";
echo "            eventSource.onmessage = function(event) {";
echo "                try {";
echo "                    const data = JSON.parse(event.data);";
echo "                    processarMensagem(data);";
echo "                } catch (error) {";
echo "                    log(`❌ Erro ao processar mensagem: ${error.message}`);";
echo "                }";
echo "            };";
echo "";
echo "            eventSource.onerror = function(error) {";
echo "                log('❌ Erro na conexão SSE');";
echo "                pararTeste();";
echo "            };";
echo "        }";
echo "";
echo "        function processarMensagem(data) {";
echo "            log(`📨 Mensagem recebida: ${data.status || 'progresso'}`);";
echo "";
echo "            switch (data.status) {";
echo "                case 'starting':";
echo "                    atualizarStatus('Iniciando cotação...');";
echo "                    atualizarProgresso(0);";
echo "                    break;";
echo "";
echo "                case 'started':";
echo "                    atualizarStatus('RPA iniciado - Processando...');";
echo "                    break;";
echo "";
echo "                case 'completed':";
echo "                    atualizarStatus('✅ Cotação concluída!');";
echo "                    atualizarProgresso(100);";
echo "                    mostrarResultadoFinal(data.progresso);";
echo "                    pararTeste();";
echo "                    break;";
echo "";
echo "                case 'timeout':";
echo "                    atualizarStatus('⏰ Timeout - Cotação cancelada');";
echo "                    pararTeste();";
echo "                    break;";
echo "";
echo "                case 'error':";
echo "                    atualizarStatus('❌ Erro na cotação');";
echo "                    log(`❌ Erro: ${data.message}`);";
echo "                    pararTeste();";
echo "                    break;";
echo "";
echo "                default:";
echo "                    // Dados de progresso normal";
echo "                    if (data.etapa_atual !== undefined) {";
echo "                        processarProgresso(data);";
echo "                    }";
echo "                    break;";
echo "            }";
echo "        }";
echo "";
echo "        function processarProgresso(data) {";
echo "            const percentual = Math.round(data.percentual || 0);";
echo "            const etapa = data.etapa_atual || 0;";
echo "            const status = data.status || 'Processando...';";
echo "";
echo "            atualizarProgresso(percentual);";
echo "            atualizarStatus(`${status} (${etapa}/15)`);";
echo "";
echo "            log(`📊 Etapa ${etapa}: ${status} (${percentual}%)`);";
echo "";
echo "            // Mostrar estimativas na Etapa 5";
echo "            if (etapa === 5 && data.details && data.details.estimativas) {";
echo "                mostrarEstimativas(data.details.estimativas);";
echo "            }";
echo "        }";
echo "";
echo "        function atualizarProgresso(percentual) {";
echo "            const progressBar = document.getElementById('progress-bar');";
echo "            progressBar.style.width = percentual + '%';";
echo "        }";
echo "";
echo "        function atualizarStatus(texto) {";
echo "            document.getElementById('status-text').textContent = texto;";
echo "        }";
echo "";
echo "        function mostrarEstimativas(estimativas) {";
echo "            const container = document.getElementById('estimativas-container');";
echo "            container.innerHTML = `";
echo "                <div class='estimativas-box'>";
echo "                    <h3>📊 Estimativas Iniciais</h3>";
echo "                    <div class='estimativas-grid'>";
echo "                        <div class='estimativa-item'>";
echo "                            <span class='label'>Valor Estimado:</span>";
echo "                            <span class='valor'>${estimativas.valor_estimado || 'N/A'}</span>";
echo "                        </div>";
echo "                        <div class='estimativa-item'>";
echo "                            <span class='label'>Franquia:</span>";
echo "                            <span class='valor'>${estimativas.franquia || 'N/A'}</span>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "            `;";
echo "            container.style.display = 'block';";
echo "            log('📊 Estimativas exibidas');";
echo "        }";
echo "";
echo "        function mostrarResultadoFinal(progresso) {";
echo "            const container = document.getElementById('resultado-container');";
echo "            const planos = progresso.details?.planos || {};";
echo "";
echo "            container.innerHTML = `";
echo "                <div class='resultado-final'>";
echo "                    <h3>🎉 Cotação Concluída!</h3>";
echo "                    <div class='planos-grid'>";
echo "                        <div class='plano-item recomendado'>";
echo "                            <h4>Plano Recomendado</h4>";
echo "                            <div class='valor-principal'>" . ($planos['plano_recomendado']['valor'] ?? 'N/A') . "</div>";
echo "                            <div class='franquia'>Franquia: " . ($planos['plano_recomendado']['valor_franquia'] ?? 'N/A') . "</div>";
echo "                        </div>";
echo "                        <div class='plano-item alternativo'>";
echo "                            <h4>Plano Alternativo</h4>";
echo "                            <div class='valor-principal'>" . ($planos['plano_alternativo']['valor'] ?? 'N/A') . "</div>";
echo "                            <div class='franquia'>Franquia: " . ($planos['plano_alternativo']['valor_franquia'] ?? 'N/A') . "</div>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "            `;";
echo "            container.style.display = 'block';";
echo "            log('🎉 Resultado final exibido');";
echo "        }";
echo "";
echo "        function pararTeste() {";
echo "            if (eventSource) {";
echo "                eventSource.close();";
echo "                eventSource = null;";
echo "                log('🛑 Teste parado');";
echo "            }";
echo "";
echo "            document.getElementById('btn-iniciar').disabled = false;";
echo "            document.getElementById('btn-parar').disabled = true;";
echo "        }";
echo "";
echo "        // Limpar log ao carregar";
echo "        window.onload = function() {";
echo "            log('📱 Página carregada - Pronto para teste');";
echo "        };";
echo "    </script>";
echo "</body>";
echo "</html>";
?>
